source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RCStarActivityIndicatorView_Example', :exclusive => true do
  pod 'RCStarActivityIndicatorView', :path => '../'
end

target 'RCStarActivityIndicatorView_Tests', :exclusive => true do
  pod 'RCStarActivityIndicatorView', :path => '../'

  
end
